#!/usr/bin/env node
import { writeFileSync } from 'fs';
import { config } from 'dotenv';
// Load .env file
config();
console.log('Generating config.js...');
console.log('VITE_MODEL_NAME:', process.env.VITE_MODEL_NAME || 'Missing');
// SECURITY: never emit the API key into dist/config.js or any other file served
// to the browser. The key stays server-side (OPENROUTER_API_KEY) and server.js
// injects it into the upstream Authorization header.
const configContent = `// Runtime configuration - Auto-generated by generate-config.js
// Do NOT add API keys here: this file is served publicly.
window.__APP_CONFIG__ = {
  modelName: '${process.env.VITE_MODEL_NAME || ''}'
};
`;
// Write to dist/config.js (after build)
writeFileSync('dist/config.js', configContent);
console.log('✓ Generated dist/config.js (no credentials)');
